### ISSUE TITLE
jar paths

### ISSUE THREAD

**Issue by fpolar** [cchyung/froggerz#1]
Can you make your paths local to the projects from now on? right now the path to the jre and sql jar are for your desktop so it'll break on anyone else's.

**Comment by kpuricelli** [comment]
Whoops thought I did. My bad.

**Comment by fpolar** [comment]
No problem! I'll clone it and try again once you push again. I just trying to test my front end stuff with your back end so no rush.

**Comment by kpuricelli** [comment]
Should be good now. Let me know / open another issue if it isn't working right.
